blog/urls.py
from django.conf.urls import url
from . import views

app_name='blog'
urlpatterns = [
	#url(r'^$', views.home, name='home')
	url(r'^$', views.post_list, name='post_list'),
	url(r'^detail/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
	url(r'^new/$', views.new_post, name='new_post'),
	url(r'^(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit')
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog import views

urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^admin/', admin.site.urls),
	url(r'^posts/', include('blog.urls'))
]

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=200)
	text = models.TextField()
	created_date = models.DateTimeField(default=timezone.now)
	published_date = models.DateTimeField(blank=True, null=True)


	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.title

	

blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ('title', 'text', )

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from django.utils import timezone
from .forms import PostForm


def home(request):
	return render(request, 'blog/home.html', {})


def post_list(request):
	posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
	return render(request, 'blog/post_list.html', {'posts': posts})


def post_detail(request, pk):
	post = get_object_or_404(Post, pk=pk)
	return render(request, 'blog/post_detail.html', {"post": post})


def new_post(request):
	if request.method == "POST":
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.published_date = timezone.now()
			post.save()
			return redirect('blog:post_detail', pk=post.pk)
	else:
		form = PostForm()
	return render(request, 'blog/new_post.html', {'form': form})


def post_edit(request, pk):
	post = get_object_or_404(Post, pk=pk)
	if request.method=="POST":
		form = PostForm(request.POST, instance=post)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.published_date = timezone.now()
			post.save()
			return redirect('blog:post_detail', pk=post.pk)
	else:
		form = PostForm(instance=post)
	return render(request, 'blog/post_edit.html', {"form": form})

blog/templates/blog/home.html
<!DOCTYPE html>
<html>
	<head>
		<title>Welcome | index</title>
	</head>
	<body>
		<h2>Welcome to my blog</h2>
		<p>A testing goat</p>
	</body>
</html>

blog/templates/blog/layout.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
		<link rel="stylesheet" href="{% static 'css/blog.css' %}">
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="page-header">
					    <h1><a href="/">My Blog</a></h1>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
		    <div class="row">
		        <div class="col-md-12">
		           {% block content %}
		           {% endblock %}
		        </div>
		    </div>
		</div>
	</body>
</html>

blog/templates/blog/new_post.html
{% extends 'layout.html' %}
{% block title %}Blog | New Post{% endblock %}

{% block page_header %}
<h1 class="text-center">Create a new post</h1>
{% endblock %}

{% block content %}
<form action="" method="POST" role="form">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" class="btn btn-primary" name="submit" value="Post Now">	
</form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'layout.html' %}
{% block title %}Post | Detail {% endblock %}

{% block page_header %}
<h1 class="text-center">Post Detail</h1>
{% endblock %}

{% block content %}
	<h1>{{ post.title }}</h1>
	<p>
		{{ post.author }}
		{% if post.published_date %}
		<span class="date">{{ post.published_date }}</span>
		{% if user.is_authenticated %}
			<a class="btn-xs btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
		{% endif %}
	</p>
	{% endif %}
	<p>{{ post.text|linebreaksbr }}</p>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'layout.html' %}
{% block title %}Blog | New Post{% endblock %}

{% block page_header %}
<h1 class="text-center">Edit Post</h1>
{% endblock %}

{% block content %}
<form action="" method="POST" role="form">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" class="btn btn-primary" name="submit" value="Update">	
</form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'layout.html' %}
{% block title %}Posts | Blog{% endblock %}

{% block page_header %}
<h1 class="text-center">Post list</h1>
{% endblock %}

{% block content %}
    
    {% if user.is_authenticated %}
	   <a href="{% url 'blog:new_post' %}" class="btn-xs btn-primary"> <span class="glyphicon glyphicon-plus"></span></a>
    {% endif %}

	{% for post in posts %}
    <div class="post">
        <div class="date">
            <p>published: {{ post.published_date }}</p>
        </div>
        <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
	{% endfor %}
{% endblock %}

blog/templates/home.html
<!DOCTYPE html>
<html>
	<head>
		<title>Welcome | index</title>
	</head>
	<body>
		<h2>Welcome to my blog</h2>
		<p>A testing goat</p>
	</body>
</html>

blog/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
		<link rel="stylesheet" href="{% static 'css/blog.css' %}">
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="page-header">
					    <h1><a href="/">My Blog</a></h1>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					{% block page_header %}
					{% endblock %}
				</div>
			</div>
		</div>
		<div class="container">
		    <div class="row">
		        <div class="col-md-12">
		           {% block content %}
		           {% endblock %}
		        </div>
		    </div>
		</div>
	</body>
</html>